# Model
model:
  rest_name: mtlssource
  resource_name: mtlssources
  entity_name: MTLSSource
  package: a3s
  group: authn/source
  description: An MTLS Auth source can be used to issue tokens based on user certificates.
  get:
    description: Get a particular mtlssource object.
  update:
    description: Update a particular mtlssource object.
  delete:
    description: Delete a particular mtlssource object.
  extends:
  - '@sharded'
  - '@identifiable'
  - '@importable'

# Indexes
indexes:
- - namespace
  - name
- - fingerprints
- - subjectKeyIDs

# Attributes
attributes:
  v1:
  - name: CA
    description: The Certificate authority to use to validate user certificates in PEM format.
    type: string
    exposed: true
    stored: true
    required: true
    example_value: |-
      -----BEGIN CERTIFICATE-----
      MIIBZTCCAQugAwIBAgIRANYvXLTa16Ykvc9hQ4BBLJEwCgYIKoZIzj0EAwIwEjEQ
      MA4GA1UEAxMHQUNNRSBDQTAeFw0yMTExMDEyMzAwMTlaFw0zMTA5MTAyMzAwMTla
      MBIxEDAOBgNVBAMTB0FDTUUgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASa
      7wknroxwB1znupZ67NzTG9Kuc+tNRlbI22eTDNMKYpIexzWDOyiQ95N3GQIdmAz5
      wVu9l2V3VuKUpD9mNgkRo0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUw
      AwEB/zAdBgNVHQ4EFgQURIT2kL76vMj9A3r9AUnaiHnHf4EwCgYIKoZIzj0EAwID
      SAAwRQIgS4SGaJ/B1Ul88Jal11Q5BwiY9bY2y9w+4xPNBxSyAIcCIQCSWVq+00xS
      bOmROq+EsxO4L/GzJx7MBbeJ6x142VKSBQ==
      -----END CERTIFICATE-----
    validations:
    - $pem

  - name: description
    description: The description of the object.
    type: string
    exposed: true
    stored: true

  - name: fingerprints
    description: The fingerprint of the CAs in the chain.
    type: list
    exposed: true
    subtype: string
    stored: true
    read_only: true
    autogenerated: true

  - name: modifier
    description: |-
      Contains optional information about a remote service that can be used to modify
      the claims that are about to be delivered using this authentication source.
    type: ref
    exposed: true
    subtype: identitymodifier
    stored: true
    omit_empty: true
    extensions:
      noInit: true
      refMode: pointer

  - name: name
    description: The name of the source.
    type: string
    exposed: true
    stored: true
    required: true
    example_value: mypki

  - name: subjectKeyIDs
    description: Value of the CAs X.509 SubjectKeyIDs in the chain.
    type: list
    exposed: true
    subtype: string
    stored: true
    read_only: true
    autogenerated: true
