# Model
model:
  rest_name: permissions
  resource_name: permissions
  entity_name: Permissions
  package: a3s
  group: authz/check
  description: API to retrieve the permissions from a user identity.

# Attributes
attributes:
  v1:
  - name: ID
    description: The optional ID of the object to check permission for.
    type: string
    exposed: true

  - name: IP
    description: IP of the client.
    type: string
    exposed: true

  - name: claims
    description: The list of claims.
    type: list
    exposed: true
    subtype: string
    required: true
    example_value:
    - sourcetype=mtls
    - sourcename=my-source
    - sourcenamespace=/my/namespace
    - color=blue
    - size=big

  - name: error
    description: Return an eventual error.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    omit_empty: true

  - name: namespace
    description: The namespace where to check permission from.
    type: string
    exposed: true
    required: true
    example_value: /acme

  - name: permissions
    description: The computed permissions.
    type: external
    exposed: true
    subtype: map[string]map[string]bool
    read_only: true
    autogenerated: true
    omit_empty: true

  - name: restrictedNamespace
    description: Sets the namespace restrictions that should apply.
    type: string
    exposed: true
    example_value: /namespace

  - name: restrictedNetworks
    description: Sets the networks restrictions that should apply.
    type: list
    exposed: true
    subtype: string
    example_value:
    - 10.0.0.0/8

  - name: restrictedPermissions
    description: Sets the permissions restrictions that should apply.
    type: list
    exposed: true
    subtype: string
    example_value:
    - '@auth:role=enforcer'
