apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: a3s-secrets
data:
  # TLS
  server-cert.pem: {{ required "global.server.cert is required" .Values.global.server.cert | quote }}
  server-key.pem: {{ required "global.server.key is required" .Values.global.server.key | quote }}
  server-key.pass: {{ required "global.server.pass is required" .Values.global.server.pass | b64enc | quote }}
  
  # JWT
  jwt-cert.pem: {{ required "global.jwt.cert is required" .Values.global.jwt.cert | quote }}
  jwt-key.pem: {{ required "global.jwt.key is required" .Values.global.jwt.key | quote }}
  jwt-key.pass: {{ required "global.jwt.pass is required" .Values.global.jwt.pass | b64enc | quote }}

  # Mongo
  mongo-ca.pem: {{ .Values.global.mongo.tls.ca | quote }}
  mongo-full.pem: {{ .Values.global.mongo.tls.full | quote }}
  mongo-cert.pem: {{ .Values.global.mongo.tls.cert | quote }}
  mongo-key.pem: {{ .Values.global.mongo.tls.key | quote }}
  mongo-key.pass: {{ .Values.global.mongo.tls.pass | b64enc | quote }}
  attribute-encryption-key.pass: {{ required "global.mongo.attributeEncryptionKey is required" .Values.global.mongo.attributeEncryptionKey | b64enc | quote }}

  # Nats
  nats-ca.pem: {{ required "global.nats.tls.ca is required" .Values.global.nats.tls.ca | quote }}
  nats-cert.pem: {{ required "global.nats.tls.cert is required" .Values.global.nats.tls.cert | quote }}
  nats-key.pem: {{ required "global.nats.tls.key is required" .Values.global.nats.tls.key | quote }}
  nats-key.pass: {{ required "global.nats.tls.pass is required" .Values.global.nats.tls.pass | b64enc | quote }}
  nats.user: {{ required "global.nats.user is required" .Values.global.nats.user | b64enc | quote }}
  nats.pass: {{ required "global.nats.pass is required" .Values.global.nats.pass | b64enc | quote }}


  
