apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: a3s-secrets
data:
  # TLS
  a3s-tls-cert.pem: {{ required "global.server.cert is required" .Values.global.server.cert | quote }}
  a3s-tls-key.pem: {{ required "global.server.key is required" .Values.global.server.key | quote }}
  a3s-tls-key.pass: {{ required "global.server.pass is required" .Values.global.server.pass | b64enc | quote }}
  
  # JWT
  jwt-cert.pem: {{ required "global.server.cert is required" .Values.global.server.cert | quote }}
  jwt-key.pem: {{ required "global.server.key is required" .Values.global.server.key | quote }}
  jwt-key.pass: {{ required "global.server.pass is required" .Values.global.server.pass | b64enc | quote }}

  # Mongo
  attribute-encryption-key.pass: {{ required "global.mongo.attributeEncryptionKey is required" .Values.global.mongo.attributeEncryptionKey | b64enc | quote }}

  # Nats
  nats.user: {{ required "global.nats.user is required" .Values.global.nats.user | b64enc | quote }}
  nats.pass: {{ required "global.nats.pass is required" .Values.global.nats.pass | b64enc | quote }}

  
